### ISSUE TITLE
your problem link/color is wrong!

### ISSUE THREAD

**Issue by TOBapNw-cjn** [atcoder-for-chinese-developers/atcoder-for-chinese#64]
some abc links to arc.
some problems are linked incorrectly.
some difficultys are displayed incorrectly.

all bugs are between abc042 and abc125 problem C or D

**Comment by e3c8f1a924** [comment]
https://github.com/atcoder-for-chinese-developers/atcoder-for-chinese/blob/a13a5aaf32b07030cf525e68de788b3d9bc85c19/func.js#L133 这边的问题。应该把整个 atcoder problems 的数据爬下来。

**Comment by e3c8f1a924** [comment]
https://github.com/atcoder-for-chinese-developers/spiders

可以用这个（宣传）

**Comment by psz2007** [comment]
fixed with commit ea22c5a01eaa1d0e5abe48994c377be750a1e660
